os: linux

dist: bionic

language: python

python:
    - 3.6

before_install:
    - pip3 install --upgrade -r requirements.txt
    - make check

install:
    - python3 setup.py install

script:
    - make installcheck
